### ISSUE TITLE
Don't show Modal when redirected through skill example

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/chat.susi.ai#1522] opened 2018-08-11 04:36 UTC
**Actual Behaviour**

![image](https://user-images.githubusercontent.com/21199234/43988195-d9a4113c-9d4d-11e8-8585-5ea7ebfe9b33.png)

**Expected Behaviour**

![image](https://user-images.githubusercontent.com/21199234/43988201-f6fa5f70-9d4d-11e8-8803-d415f5de0370.png)

**Steps to reproduce it**
Click on skill example card on skills.susi.ai

**Would you like to work on the issue?**

Yes

**Comment by anshumanv** [comment] 2018-08-11 04:37
Thanks for this @aashutoshrathi

**Comment by rupav** [comment] 2018-09-19 17:13
Its fixed, not showing modal anymore. This can be closed @anshumanv @aashutoshrathi

**Comment by akshatnitd** [comment] 2018-09-19 17:15
Yes, even I am not able to reproduce the bug. Hence, closing.

**Closed by akshatnitd** 2018-09-19 17:15 UTC
Labels: UI/UX, bug
