### ISSUE TITLE
Modify Custom Theme

### ISSUE THREAD

**Issue by fragm3** [fossasia/chat.susi.ai#1471] opened 2018-07-19 15:18 UTC
**Actual Behaviour**

As said by @mariobehling in https://github.com/fossasia/chat.susi.ai/issues/1461

**Expected Behaviour**

- [ ] Add custom theme in settings
- [ ] Add live preview
- [ ] Fix bug like background images not resetting(see in chat.susi.ai by setting background image, then try removing it

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment] 2018-07-24 15:16
This is mostly a duplicate of #1461

**Closed by mariobehling** 2018-07-24 15:16 UTC
