### ISSUE TITLE
cannot answer follow up questions

### ISSUE THREAD

**Issue by Nathandrake229** [fossasia/chat.susi.ai#2011] opened 2019-01-28 15:07 UTC
**Actual Behaviour**
me- who is the president of USA?
susi.ai- Donald Trump (from 20. January 2017 to present)
me- what is his height?
susi.ai- The explanation for this question can take a while, I'll let you know the answer later.

**Expected Behaviour**
me- who is the president of USA?
susi.ai- Donald Trump (from 20. January 2017 to present)
me- what is his height?
susi.ai- his height is 6'3"

**Steps to reproduce it**

just ask any follow up questions as the one given above. the following question must be related to the first question you ask

**Would you like to work on the issue?**

yes

**Comment by AakashMallik** [comment] 2019-01-28 15:25
@Nathandrake229 Not a bug, this should either be raised on the server repo or it should be addressed as a new skill that you should create, for which creating an issue is not needed.

**Comment by plxity** [comment] 2019-01-30 12:32
@Nathandrake229 close this issue.

**Comment by Nathandrake229** [comment] 2019-01-30 12:49
Can you please give me the brief way to approach this issue?
Am new to this community.
Any guidance would be a big help

**Closed** 2019-01-30 13:31 UTC
