### ISSUE TITLE
Remove SUSI.AI legacy susi.ai/chat

### ISSUE THREAD

**Issue by tabesin** [fossasia/chat.susi.ai#815] opened 2017-09-20 07:32 UTC
While a running installation is at https://chat.susi.ai a Google Search points to an older sysfunctional incarnation of Susi.ai https://susi.ai/chat

1) pull the outdated install
2) pin https://susi.ai/chat traffic to https://chat.susi.ai

**Comment by Remorax** [comment] 2017-09-25 18:15
@tabesin, the issue is not clear. Could you please elaborate, and post a screenshot or something?

**Comment by tabesin** [comment] 2017-09-25 22:53
Follow the two links, if there are still questions, find someone who explains you.

**Comment by abishekvashok** [comment] 2017-12-03 09:17
@tabesin I think this is fixed now,
https://susi.ai/chat points to https://chat.susi.ai

**Closed** 2018-05-24 22:49 UTC
Labels: Hacktoberfest
