### ISSUE TITLE
Profile image not visible when in the settings page

### ISSUE THREAD

**Issue by prateek76** [fossasia/chat.susi.ai#2077] opened 2019-04-15 17:39 UTC
**Actual Behaviour**

The Profile image not visible when in the settings page
**Expected Behaviour**

The profile image should be visible when in the settings page

**Steps to reproduce it**

Open https://chat.susi.ai/settings and see the profile image in the 

top right corner

**Screenshots of the issue**

![profile picture not visible in the settings page](https://user-images.githubusercontent.com/33982495/56153324-8116bd00-5fd3-11e9-99b6-eb91abc14f49.PNG)

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment] 2019-05-27 11:03
Duplicate of https://github.com/fossasia/chat.susi.ai/issues/1837, closing.

**Closed by fragm3** 2019-05-27 11:03 UTC
