### ISSUE TITLE
Left tabs and menu paper in Settings exceed the presence of text

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [fossasia/chat.susi.ai#1017] opened 2018-01-09 15:30 UTC
**Actual Behaviour**

The side nav and the menu paper on the Settings page extend to more than what is required when the user is logged out of susi. For instance, when the user is logged out, mere 8 side nav options are displayed whereas the background paper exceeds to fit 11 (which is the number of options one can navigate when the user is logged in).

**Expected Behaviour**

The side nav and menu paper on the Settings page should adjust to the amount of content displayed, depending upon whether the user is logged in.

**Steps to reproduce it**

Log out of susi and open the Settings page to see the extended background paper.

**Screenshots of the issue**

![screen shot 2018-01-09 at 8 44 42 pm](https://user-images.githubusercontent.com/29275810/34728501-1346db5c-f580-11e7-8f72-d54a10676da9.png)

**Would you like to work on the issue?**

Yes, I'd like to work on this.

**Comment by codingblazer** [comment] 2018-01-09 18:32
Hi this is duplicate of #1007. I have already sent PR for it.

**Comment by VibhorCodecianGupta** [comment] 2018-01-10 10:48
@codingblazer it is not because from what I understand, you fixed the mobile view but you still put 550px as the case otherwise. What I have done here is different. When a user is logged in, the menu paper fits beautifully. But when a user is logged out, the menu paper extends because it is set to 550px, when it only requires about 400px.
I fixed this issue. The code in #1018 gets the cookies. If present, the height of the menu paper is set 550, otherwise 400. Similarly, the height of the side tabs is set to `auto` which automatically takes care of stuff.

**Comment by VibhorCodecianGupta** [comment] 2018-01-28 14:33
I opened a fresh PR for this particular issue as the older PR had gotten messy with a complex git workflow :)

**Closed** 2018-05-26 05:48 UTC
